// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://lfj6velfqjgi5hojuhzusqsg2q.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-i5hwcdtrvvakzbgiegjh4cifzi",
    "aws_cloud_logic_custom": [
        {
            "name": "api6aeb77be",
            "endpoint": "https://mujt0j8pm9.execute-api.eu-west-1.amazonaws.com/develop",
            "region": "eu-west-1"
        }
    ],
    "aws_content_delivery_bucket": "stream4thewin-20200214102706-hostingbucket-develop",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d2o12eq21my63z.cloudfront.net",
    "aws_cognito_identity_pool_id": "eu-west-1:8e7f5acc-5c81-4741-8acd-258b53192dac",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_qorZ49BOa",
    "aws_user_pools_web_client_id": "79e6mt6il6i9p8983lk333gkjd",
    "oauth": {}
};


export default awsmobile;
